### ISSUE TITLE
stpSynapse not found in STP_NML2.nml file

### ISSUE THREAD

**Issue by adrianq** [OpenSourceBrain/IzhikevichModel#5]
stpSynapse can't be found in [file](https://github.com/OpenSourceBrain/IzhikevichModel/blob/master/neuroConstruct/cellMechanisms/STP_NML2/STP_NML2.nml). Non valid neuroml file

**Comment by pgleeson** [comment]
Removed neuroConstruct project from this repo as was very out of date. STP_NML2.nml gone...
